# BEFORE USAGE:
# PUT:
# fake-s3  127.0.0.1
# to your /etc/hosts
# And create s3_sandbox directory (or remove volume creation)
version: '2.1'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  fake-s3:
    image: lphoward/fake-s3
    volumes:
      - "./s3_sandbox:/fakes3_root"
    ports:
      - "4569:4569"
    hostname: fake-s3